"""Held-out evaluation phrases — never add these to training_data.py."""

HELDOUT = [
    ("the pipe under the bathroom basin is dripping", "plumbing"),
    ("water heater makes a popping noise", "plumbing"),
    ("kitchen sink is completely blocked", "plumbing"),
    ("toilet tank does not refill after flushing", "plumbing"),
    ("motor is pumping air not water", "plumbing"),
    ("socket in the bedroom stopped working", "electrical"),
    ("light switch sparks when turned on", "electrical"),
    ("install a new fan and two lights", "electrical"),
    ("the main breaker trips at night", "electrical"),
    ("cupboard shelves collapsed", "carpentry"),
    ("door is swollen and rubs against the frame", "carpentry"),
    ("make a wooden tv cabinet", "carpentry"),
    ("repaint the kitchen in a lighter colour", "painting"),
    ("damp patches made the paint bubble", "painting"),
    ("freezer is frosting up and fridge is warm", "appliance"),
    ("oven does not heat up", "appliance"),
    ("washing machine drum will not turn", "appliance"),
    ("inverter ac shows an error and stops cooling", "hvac"),
    ("need to service two split units", "hvac"),
    ("gas heater won't ignite", "hvac"),
    ("deep cleaning of the kitchen and fridge", "cleaning"),
    ("sofa covers and rugs need washing", "cleaning"),
    ("lay new marble in the lounge", "masonry"),
    ("wall has a big crack after the earthquake", "masonry"),
    ("ceiling leaks every time it rains", "roofing"),
    ("roof tank area seepage into the room below", "roofing"),
    ("white ants found in the door frame", "pest_control"),
    ("mosquitoes breeding in the lawn", "pest_control"),
    ("bed bugs biting at night", "pest_control"),
    ("cannot open the front door, lock broken", "locksmith"),
    ("need spare keys and a new padlock", "locksmith"),
    ("put up curtains and blinds", "general"),
    ("assemble a bookshelf and a desk", "general"),
    ("microwave display is dead", "appliance"),
    ("tap water pressure dropped suddenly", "plumbing"),
    ("tube light flickers", "electrical"),
]
