"""Labelled examples for the problem-description classifier.

Two sources of evidence per category:

* ``LEXICON`` – strong keywords/phrases (also used by the backend's JS
  fallback in backend/src/services/scoring.js — keep the lists in sync).
* ``SAMPLES`` – realistic customer descriptions. Add more lines here to
  teach the model new phrasings; it retrains on startup.
"""

LEXICON = {
    "plumbing": ["leak", "pipe", "faucet", "tap", "sink", "drain", "clog", "blocked", "toilet", "flush", "shower",
                 "geyser", "valve", "sewage", "sewer", "plumber", "basin", "water tank", "water pump", "drip",
                 "water pressure", "overflow", "cistern", "commode", "bathroom", "water heater", "hot water"],
    "electrical": ["wiring", "wire", "socket", "switch", "outlet", "breaker", "fuse", "circuit", "short circuit",
                   "light", "bulb", "ceiling fan", "fan", "power", "electricity", "voltage", "electrician", "spark",
                   "shock", "ups", "inverter", "generator", "meter", "tripping", "chandelier", "led", "electric",
                   "db box"],
    "carpentry": ["wood", "door", "cabinet", "cupboard", "wardrobe", "furniture", "table", "chair", "shelf",
                  "drawer", "hinge", "carpenter", "bed", "wooden", "deck", "window frame", "door frame", "laminate",
                  "plywood", "kitchen cabinet"],
    "painting": ["paint", "wall paint", "colour", "color", "primer", "coat", "painter", "whitewash", "distemper",
                 "enamel", "wallpaper", "peeling", "putty", "texture", "repaint", "emulsion"],
    "appliance": ["washing machine", "fridge", "refrigerator", "freezer", "oven", "microwave", "dishwasher", "dryer",
                  "stove", "cooker", "appliance", "television", "tv", "iron", "blender", "water dispenser", "vacuum",
                  "deep freezer"],
    "hvac": ["ac", "air conditioner", "air conditioning", "cooling", "heating", "heater", "furnace", "thermostat",
             "duct", "vent", "hvac", "compressor", "gas refill", "split ac", "chiller", "ventilation", "heat pump",
             "not cooling"],
    "cleaning": ["clean", "cleaning", "deep clean", "carpet", "sofa", "mop", "dust", "sanitize", "maid",
                 "tank cleaning", "grease", "mold", "mould", "upholstery", "pressure wash", "disinfect", "cleaner"],
    "masonry": ["tile", "tiling", "brick", "cement", "concrete", "plaster", "crack", "grout", "marble", "floor",
                "flooring", "mason", "stone", "granite", "foundation", "boundary wall"],
    "roofing": ["roof", "roofing", "gutter", "shingle", "waterproofing", "seepage", "terrace", "skylight", "chimney",
                "rain water", "roof leak", "ceiling leak", "damp"],
    "pest_control": ["pest", "termite", "cockroach", "roach", "ant", "rat", "mouse", "mice", "rodent", "bed bug",
                     "bug", "mosquito", "insect", "fumigation", "wasp", "lizard", "spray"],
    "locksmith": ["lock", "locked", "key", "locksmith", "lockout", "deadbolt", "padlock", "latch", "door lock",
                  "smart lock", "locked out", "safe"],
    "general": ["install", "mount", "assemble", "assembly", "hang", "curtain", "rod", "handyman", "tv mount",
                "picture", "odd job", "small repair", "general"],
}

SAMPLES = {
    "plumbing": [
        "Water is leaking from the pipe under my kitchen sink",
        "The toilet keeps running and will not stop flushing",
        "Bathroom drain is blocked and water is not going down",
        "Kitchen tap is dripping all night",
        "Geyser is not giving hot water anymore",
        "Water pressure in the shower is very low",
        "Commode is clogged and overflowing",
        "Need a new mixer tap installed in the bathroom",
        "Water tank overflows every time the motor runs",
        "Sewage smell coming from the floor drain",
        "Washbasin pipe burst and water everywhere",
        "Install a water filter under the sink",
        "The cistern is cracked and leaking onto the floor",
        "Hot water pipe making knocking noises",
        "Water pump motor runs but no water reaches the roof tank",
        "Shower head and valve need replacing",
        "Gutter pipe from the bathroom is leaking into the wall",
        "Bad smell from the kitchen drain and slow draining water",
        "Bathroom floor trap stinks and gurgles",
    ],
    "electrical": [
        "Sparks coming out of the socket when I plug something in",
        "The breaker keeps tripping when the iron is on",
        "Half the lights in the house stopped working",
        "Need a ceiling fan installed in the bedroom",
        "Install a new distribution box with breakers",
        "UPS is not charging the batteries",
        "Switch board is burnt and smells of plastic",
        "Fan is making noise and running slowly, maybe the capacitor",
        "Need wiring for a new room extension",
        "Voltage fluctuates and bulbs keep fusing",
        "Install LED lights and a chandelier in the lounge",
        "Electric meter shows a fault and there is no power upstairs",
        "Short circuit in the kitchen, the fuse blew",
        "Need extra sockets in the study",
        "Solar inverter wiring needs checking",
        "Doorbell and outdoor lights are not working",
    ],
    "carpentry": [
        "Kitchen cabinet doors are hanging loose, hinges broken",
        "Wooden door is stuck and will not close properly",
        "Need a wardrobe assembled and fixed to the wall",
        "Bed frame is broken and squeaks",
        "Make a custom shelf for books",
        "Drawer slides are broken in the dressing table",
        "Window frame wood is rotten and needs replacing",
        "Repair a wobbly dining table and chairs",
        "Door lock area of the wooden door is cracked",
        "Install wooden flooring laminate in the bedroom",
        "Cupboard door came off its hinge",
        "Polish and repair old wooden furniture",
        "Fit a new main door with frame",
        "Build a wooden deck on the terrace",
    ],
    "painting": [
        "Need the bedroom walls repainted with two coats",
        "Paint is peeling off the living room wall",
        "Whitewash the whole house before the wedding",
        "Apply putty and paint on the cracked walls",
        "Paint the front gate with enamel",
        "Want a texture paint finish on the TV wall",
        "Exterior walls need weather shield paint",
        "Change the colour of the kids room to light blue",
        "Remove old wallpaper and paint the wall",
        "Distemper the ceiling and walls of three rooms",
        "Stains on the wall after seepage, need repainting",
        "Paint the wooden doors and window grills",
        "Paint the outside of the house and the boundary wall",
    ],
    "appliance": [
        "Washing machine stopped spinning",
        "Fridge is not cooling and the freezer has ice build up",
        "Microwave turns on but does not heat food",
        "Oven door is broken and it does not get hot",
        "Dishwasher is leaking water from the bottom",
        "Dryer makes a loud banging noise",
        "Deep freezer compressor stopped working",
        "Water dispenser is not giving cold water",
        "TV has sound but no picture",
        "Stove burner will not light",
        "Refrigerator is making a loud humming noise",
        "Automatic washing machine shows an error code",
        "Vacuum cleaner lost suction",
        "Gas stove burner flame is low and yellow",
        "Cooking range burners will not ignite",
        "Microwave makes sparks and a burning smell",
    ],
    "hvac": [
        "The split AC is not cooling and needs a gas refill",
        "Air conditioner is leaking water inside the room",
        "AC outdoor unit makes a loud noise",
        "Need AC service before summer",
        "Install a new 1.5 ton inverter AC",
        "Heater does not turn on in winter",
        "Thermostat is not working properly",
        "Central air ducts are dusty and smell bad",
        "Gas heater flame keeps going off",
        "AC remote works but compressor does not start",
        "Room ventilation is poor, need an exhaust installed",
        "Heat pump stopped heating",
        "Window AC trips the breaker after a few minutes",
    ],
    "cleaning": [
        "Need a full deep clean of a three bedroom house",
        "Sofa and carpet shampoo before guests arrive",
        "Kitchen has heavy grease on the cabinets and hood",
        "Water tank cleaning and disinfection",
        "Move out cleaning for an apartment",
        "Mold on the bathroom ceiling needs cleaning",
        "Clean the windows and glass doors",
        "Pressure wash the driveway and porch",
        "Post construction dust cleaning",
        "Regular weekly maid service",
        "Mattress and upholstery cleaning",
        "Sanitize the whole office",
    ],
    "masonry": [
        "Floor tiles are cracked and loose",
        "Need new tiles in the bathroom",
        "Big crack in the boundary wall",
        "Plaster is falling off the wall",
        "Regrout the kitchen backsplash tiles",
        "Marble floor needs grinding and polishing",
        "Build a small brick wall in the garden",
        "Concrete driveway has cracks and holes",
        "Fix the broken stairs steps",
        "Install granite countertop in the kitchen",
        "Cement work on the roof parapet",
        "Stone cladding on the front elevation",
    ],
    "roofing": [
        "Roof is leaking when it rains",
        "Water seepage from the ceiling during rain",
        "Need waterproofing on the terrace",
        "Gutters are blocked with leaves",
        "Damp patches on the top floor ceiling",
        "Replace broken roof sheets",
        "Skylight is leaking",
        "Rain water pools on the roof",
        "Roof insulation for summer heat",
        "Chimney needs repair",
        "Shingles blew off in the storm",
    ],
    "pest_control": [
        "Cockroaches all over the kitchen",
        "Termites are eating the wooden doors",
        "Rats in the store room",
        "Bed bugs in the bedroom",
        "Mosquito fumigation for the garden",
        "Ants in the kitchen cupboards",
        "Wasp nest near the window",
        "Lizards everywhere in the house",
        "Need pest spray for the whole house",
        "Mice chewing the wires in the ceiling",
        "Termite treatment before construction",
    ],
    "locksmith": [
        "I am locked out of my house",
        "Lost my house key and need a new lock",
        "Door lock is jammed and the key will not turn",
        "Install a smart lock on the main door",
        "Change all locks after moving in",
        "Key broke inside the lock",
        "Safe will not open, forgot the code",
        "Padlock on the gate is rusted shut",
        "Fit a deadbolt on the back door",
        "Car keys locked inside, need help",
    ],
    "general": [
        "Mount the TV on the wall",
        "Hang curtains and curtain rods in three rooms",
        "Assemble furniture from the store",
        "Hang pictures and mirrors",
        "Small odd jobs around the house",
        "Install a mirror and towel rails in the bathroom",
        "Put up shelves in the garage",
        "General handyman for a few hours",
        "Install window blinds",
        "Fix a few small things before we move in",
    ],
}

CATEGORY_LABELS = {
    "plumbing": "Plumbing",
    "electrical": "Electrical",
    "carpentry": "Carpentry",
    "painting": "Painting",
    "appliance": "Appliance repair",
    "hvac": "AC & heating",
    "cleaning": "Cleaning",
    "masonry": "Masonry & tiling",
    "roofing": "Roofing",
    "pest_control": "Pest control",
    "locksmith": "Locksmith",
    "general": "General handyman",
}
